### PR TITLE
[Feature] add methods get and count for both files

### PR DESCRIPTION
**Pull request by AndZapata**
Adding get method which obtains the values of a given key: class.id
Adding count method which obtains the number of classes

### CODE REVIEW

**Review by yawzyag — COMMENTED** [review]
Make sure that pep8 is ok

**Comment by AndZapata** [comment]
We just check the pep8 styles, and it seems to be done, thanks

**Review by yawzyag — COMMENTED** [review]
You need to make a test case for every case in DB and file storage

**Comment by AndZapata** [comment]
Ok, Unittest is comming soon, for both methods in both functions, thanks for remaining me that.

**Review by yawzyag — APPROVED** [review]
ok 🥇

**Pull request merged**
